// common
export const CATCH_SOME_ERROR_FAILURE = 'CATCH_SOME_ERROR_FAILURE'

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'