// common
export const CATCH_SOME_ERROR_FAILURE = 'CATCH_SOME_ERROR_FAILURE'

// counter
export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'

// search song
export const SEARCH_SONG_REQUEST = 'SEARCH_SONG_REQUEST'
export const SEARCH_SONG_FAILURE = 'SEARCH_SONG_FAILURE'
export const SEARCH_SONG_SUCCESS = 'SEARCH_SONG_SUCCESS'
